In [1]:
import numpy as np

array1 = np.array([1,2,3,4,5,6], dtype = 'int')
array1

array([1, 2, 3, 4, 5, 6])

In [3]:
type(array1)

numpy.ndarray

In [4]:
array1.dtype

dtype('int64')

In [7]:
array2 = np.array([[1,2,3],[4,5,6]], dtype = 'int', ndmin = 2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array3 = np.array([1,2,3], dtype = 'complex')
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
# np.zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# np.ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:

np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# np.arange
np.arange (0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
# reshape
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])