## Lección 2 - Tipos de datos

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4], dtype=np.int_)
a

array([1, 2, 3, 4])

In [7]:
a.dtype

dtype('int64')

In [11]:
bool_array = np.array([[1, 0, 0, 1], [0, 1, 1, 0]], dtype=np.bool)
bool_array

array([[ True, False, False,  True],
       [False,  True,  True, False]])

In [13]:
True * True 

1

In [16]:
char_array = np.array(['a','b','c'], dtype = np.chararray)
char_array

C:\Users\javie\AppData\Local\Temp\ipykernel_23928\2983660677.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  char_array = np.array(['a','b','c'], dtype = np.chararray)


array(['a', 'b', 'c'], dtype=object)

In [21]:
from sys import getsizeof

a = np.array([1,2,3,4], dtype = np.int8)
b = np.array([1,2,3,4], dtype = np.int64)

print("A", getsizeof(a))
print("b", getsizeof(b))

A 116
b 144


In [23]:
a.dtype

dtype('int8')

In [26]:
a.dtype.type is np.int8

True

In [25]:
dt = np.dtype('int32')
print(dt.type)
dt.type is np.int32

<class 'numpy.int32'>


True

In [28]:
np.nan

nan

In [29]:
np.isnan(np.nan)

np.True_

In [31]:
np.array([1,2,3,np.nan,4])

array([ 1.,  2.,  3., nan,  4.])

## Matrix


In [33]:
m = np.matrix('1 2 3 ; 4 5 6 ', dtype=np.float16)
m

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)

In [37]:
a = np.array([[1,2,3],[4,5,6]], dtype=np.float16)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)