In [2]:
import numpy as np

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[4]

np.int64(4)

In [9]:
a.shape

(10,)

In [11]:
a[9]

np.int64(9)

## Slicing

In [13]:
a[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a[0:9:2]

array([0, 2, 4, 6, 8])

In [18]:
a[-2:10]

array([8, 9])

In [21]:
a[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
a = np.array([[1,2,3],[3,4,5]], dtype = np.int8)
a

array([[1, 2, 3],
       [3, 4, 5]], dtype=int8)

In [31]:
a[1][2]

np.int8(5)

In [33]:
a[1,2]

np.int8(5)

In [36]:
a[1,0:2]

array([3, 4], dtype=int8)

In [38]:
a[0:2,0:2]

array([[1, 2],
       [3, 4]], dtype=int8)

In [40]:
m = np.matrix(a)
m

matrix([[1, 2, 3],
        [3, 4, 5]], dtype=int8)

In [43]:
m[0,1] + m[1,0]

np.int8(5)

In [45]:
x = np.array([[4,3],[np.nan,2.], [np.nan, np.nan]])
x

array([[ 4.,  3.],
       [nan,  2.],
       [nan, nan]])

In [46]:
x[~np.isnan(x)]

array([4., 3., 2.])

### Indexado booleano

In [48]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [52]:
a[a>4]

array([5, 6, 7, 8, 9])

In [54]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [56]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [58]:
char_array = np.array(['OW', 'Machine Learning','Numpy'])
char_array


array(['OW', 'Machine Learning', 'Numpy'], dtype='<U16')

In [61]:
char_array == 'Numpy'

array([False, False,  True])

In [63]:
char_array[char_array == 'Numpy']


array(['Numpy'], dtype='<U16')

In [65]:
array_bool = np.array([False, False, True])
array_bool

array([False, False,  True])

In [ ]:
char_array[array_bool]

array(['Numpy'], dtype='<U16')

## Recorrido

In [68]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
for v in a:
    print(v)

0
1
2
3
4
5
6
7
8
9


In [71]:
for valor in np.nditer(a):
    print(valor)

0
1
2
3
4
5
6
7
8
9
