# Mascaras


In [1]:
import numpy as np
import numpy.ma as ma

In [ ]:
x = np.array([1, 2, 3, -1, 4])
x

array([ 1,  2,  3, -1,  4])

In [ ]:
mask_array = ma.masked_array(x, mask=[0, 0, 0, 1, 0])
mask_array

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [9]:
mask_array.min()

np.int64(1)

In [ ]:
x = ma.array([1, 2, 3, -1, 4], mask=[0, 0, 0, 1, 0])
x

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [15]:
x.compressed()

array([1, 2, 3, 4])

In [18]:
x.mask = True
x

masked_array(data=[--, --, --, --, --],
             mask=[ True,  True,  True,  True,  True],
       fill_value=999999,
            dtype=int64)

In [21]:
x.mask = False
x

masked_array(data=[1, 2, 3, -1, 4],
             mask=[False, False, False, False, False],
       fill_value=999999)

In [ ]:
x.mask = [0, 0, 0, 1, 0]
x

masked_array(data=[1, 2, 3, --, 4],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [31]:
x[3] is ma.masked

True

In [32]:
x.filled(0)

array([1, 2, 3, 0, 4])

In [36]:
x = np.array([1, 2, 3, -1, 4])

In [ ]:
ma.masked_equal(x, 4)

masked_array(data=[1, 2, 3, -1, --],
             mask=[False, False, False, False,  True],
       fill_value=4)

In [ ]:
ma.masked_not_equal(x, 2)

masked_array(data=[--, 2, --, --, --],
             mask=[ True, False,  True,  True,  True],
       fill_value=999999)

In [43]:
ma.masked_where(x < 2, x)

masked_array(data=[--, 2, 3, --, 4],
             mask=[ True, False, False,  True, False],
       fill_value=999999)

In [45]:
ma.masked_greater_equal(x, 2)

masked_array(data=[1, --, --, -1, --],
             mask=[False,  True,  True, False,  True],
       fill_value=999999)

In [47]:
ma.masked_less_equal(x, 2)

masked_array(data=[--, --, 3, --, 4],
             mask=[ True,  True, False,  True, False],
       fill_value=999999)

In [48]:
ma.masked_inside(x, 1, 3)

masked_array(data=[--, --, --, -1, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=999999)